name: Web Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run Web Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Start selenoid server
        uses: Xotabu4/selenoid-github-action@v2
        with:
          selenoid-start-arguments: |
              --browsers 'chrome' --last-versions 1

      - name: Run tests
        run: mvn clean test -Dsuite=web-testing -Dbrowser=chrome